ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_DOCUMENTTYPE_ID
ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_USER_ID
ALTER TABLE TOPIC DROP FOREIGN KEY FK_TOPIC_TOPICTYPE_ID
ALTER TABLE USER DROP FOREIGN KEY FK_USER_TEACHER_ID
DROP TABLE DOCUMENT
DROP TABLE DOCUMENT_TYPE
DROP TABLE TOPIC
DROP TABLE TOPIC_TYPE
DROP TABLE USER
DROP TABLE MENU
DROP TABLE WILL
